language: php

php:
  - 5.6
  - 7.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mecab mecab-ipadic-utf8
  - sudo apt-get install php5-dev libmecab-dev build-essential

before_script:
  - chmod +x travis-php-mecab.sh

script:
  - ./travis-php-mecab.sh

install: composer install